name: Lint

on:
  push:
    branches:
      - main
      - feature/*
  pull_request_target:
    branches:
      - main

env:
  PYTHON_VERSION: '3.13.1'

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff invoke

    - name: Run lint
      run: |
        invoke lint
